language: node_js
node_js:
 - "iojs"
install:
 - npm install --production
 - npm run build:prod
script: bash ./deploy-gh-pages.sh
env:
  global:
  - GH_REF: github.com/nanor/youtube-inbox.git
branches:
  only:
  - master